Fix verbosed and detailed stats
webpack/webpack pull request #10306
Opened 2020-01-28 14:40 UTC by smelukov

**What kind of change does this PR introduce?**

bugfix
related to https://github.com/webpack/webpack-cli/pull/1191

**Did you add tests for your changes?**

nope

**Does this PR introduce a breaking change?**

nope

**What needs to be documented once your changes are merged?**

nope

2021-01-15 14:45 UTC, sokra requested changes

2021-01-15 14:45 UTC, sokra commented on lib/Stats.js
> +					cached: true,
```suggestion
					cachedModules: true,
```

2021-01-15 14:45 UTC, sokra commented on lib/Stats.js
> +					cached: true,
```suggestion
					cachedModules: true,
```

2021-09-15 13:33 UTC, vankop commented
Thanks for your contribution. I am closing PR because it is too stale..

2021-09-15 13:33 UTC, closed without merging