fix: warnUnexpectedRequire binds wrong variable in for-loop
webpack/webpack pull request #11526
Opened 2020-09-25 03:30 UTC by tranvansang

Fix the warnUnexpectedRequire function where it uses a hoisted variable in a for-loop.

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

No. The bugfix is for a warning. I think tests are necessary.

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Nothing.

2020-09-25 07:35 UTC, sokra requested changes
Good find. Code seems correct, but it can be simplified a bit.

A test case would be great.

2020-09-25 07:35 UTC, sokra commented on lib/hmr/JavascriptHotModuleReplacement.runtime.js
>  		};
As `warnUnexpectedRequire` is a module factory it's parsed a `module` argument, which has an `id` property.

``` js
		var warnUnexpectedRequire = function warnUnexpectedRequire(module) {
			console.warn(
				"[HMR] unexpected require(" + module.id + ") to disposed module"
			);
		};
```

2020-09-25 07:35 UTC, sokra commented on lib/hmr/JavascriptHotModuleReplacement.runtime.js
> +					appliedUpdate[moduleId].isDisposed = true;
```suggestion
					appliedUpdate[moduleId] = warnUnexpectedRequire;
```

2020-09-25 07:35 UTC, sokra commented on lib/hmr/JavascriptHotModuleReplacement.runtime.js
> +					!appliedUpdate[outdatedModuleId].isDisposed) &&
```suggestion
				appliedUpdate[outdatedModuleId] !== warnUnexpectedRequire &&
```

2020-09-26 02:10 UTC, tranvansang commented
@webpack-bot thanks

@sokra I've added a test case that fails without the PR change and succeeds with the PR change. The PR is now available for review.

2020-09-27 09:29 UTC, sokra approved these changes

2020-09-28 06:48 UTC, merged

2020-09-28 06:48 UTC, sokra commented
Thanks