fix: `jsonpchunkloading` add preload script
webpack/webpack pull request #11535
Opened 2020-09-26 05:18 UTC by caoren

**What kind of change does this PR introduce?**

If a chunk is loaded，`__webpack_require__.f.j' method will time out.
Because 'webbackjsonpcallback' does not process items in 'chunkloadingglobal'.
The pr fixed.

2020-09-28 10:20 UTC, evilebottnawi requested changes
Please accept CLA and add tests

2020-10-20 12:12 UTC, theKashey commented on lib/web/JsonpChunkLoadingRuntimeModule.js
> +						"for(var i = 0; i < chunkLoadingGlobal.length; i++) webpackJsonpCallback(chunkLoadingGlobal[i]);"
a very missing feature. Blocking proper support for code splitting in `loadable-components` as long as right now or main chunk has to be loaded first, or the application will be broken.

2020-10-21 00:29 UTC, ScriptedAlchemy commented
@sokra bumping this issue for visibility.

2020-10-21 10:54 UTC, evilebottnawi commented on declarations.d.ts
> +}
Why do not use `@types/browserslist`?

2020-10-21 10:54 UTC, evilebottnawi reviewed
Also need rebase

2020-10-22 05:12 UTC, ScriptedAlchemy commented
@caoren can you rebase :)

2020-12-14 22:05 UTC, 7rulnik commented
Seems it was done in https://github.com/webpack/webpack/commit/436be4a029dd37e33f787039be53b9b5e8168026

2021-02-11 15:34 UTC, closed without merging