Bump acorn 8
webpack/webpack pull request #11552
Opened 2020-09-29 14:49 UTC by JLHwung

Bump Acorn to 8 per requested in https://github.com/webpack/webpack/pull/11550#issuecomment-700698799

**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
Yes, finally.

**Does this PR introduce a breaking change?**
No. The breaking change from acorn 7 to acorn 8 is that `ecmaVersion` is a required option.

**What needs to be documented once your changes are merged?**
No.

2020-09-29 16:09 UTC, sokra requested changes
Something seems pretty broken? CI is complaining a lot. I wonder why?

2020-09-29 16:09 UTC, sokra commented on test/cases/parsing/logical-assignment/test.filter.js
> +var supportsLogicalAssignment = require("../../../helpers/supportsLogicalAssignment");
You forgot to add this file

2020-09-30 22:54 UTC, JLHwung commented
Please restart the CI, I believe the errors are not related.

2020-10-01 22:03 UTC, JLHwung commented
Ahh the CI is not flaky. It bails because of an upstream issue: https://github.com/acornjs/acorn/issues/981

2020-10-07 08:36 UTC, merged

2020-10-07 08:36 UTC, sokra commented
Thanks