fix(normal-module-factory): improve dx on deprecation messages
webpack/webpack pull request #12037
Opened 2020-11-20 19:52 UTC by PlayMa256

**What kind of change does this PR introduce?**
When upgrading from v4 some plugins/loaders are not still updated yet so it was difficult for the end-user to track it down properly. Adding the tap name improves debug

also related to https://twitter.com/sseraphini/status/1329848098965872643

**Did you add tests for your changes?**
not needed

**Does this PR introduce a breaking change?**
no

2020-11-20 19:53 UTC, sibelius approved these changes

2020-11-20 20:11 UTC, PlayMa256 commented on lib/NormalModuleFactory.js
> +						this.hooks.beforeResolve.tap.name
actually the name comes from `this.hooks.hookName.taps[].name`, what is the best way to get the name here?

2020-11-20 20:15 UTC, PlayMa256 commented on lib/NormalModuleFactory.js
> +						this.hooks.beforeResolve.tap.name
I choose to go with taps, is there a better way anyways?

2020-11-23 08:37 UTC, sokra requested changes

2020-11-23 08:37 UTC, sokra commented on lib/NormalModuleFactory.js
> +		.join(",");
```suggestion
		.join(", ");
```

2020-11-23 08:38 UTC, sokra approved these changes

2021-01-04 14:48 UTC, sokra approved these changes

2021-01-04 15:41 UTC, snitin315 approved these changes

2021-01-18 15:02 UTC, sokra commented
Thanks

2021-01-18 15:02 UTC, merged