recognition of root path if it has the format of a network directory
webpack/webpack pull request #12212
Opened 2020-12-15 23:22 UTC by PaulDressel

Issue: Webpack did not recognize network directory paths. 

Network paths do not have ":" as second character. Unfortunately the code only tests this case for windows paths.
The consequence was the following error: 
`\\... is neither a posix nor a windows path, and there is no 'join' method defined in the file system`

To fix this issue I inserted the following condition in the if clause: 
|| rootPath.startsWith("\\\\")

**What kind of change does this PR introduce?**
- bugfix

**Does this PR introduce a breaking change?**
- No

**What needs to be documented once your changes are merged?**
- Nothing

2020-12-15 23:25 UTC, alexander-akait reviewed
Will be great to add test for this case

2020-12-17 10:26 UTC, sokra requested changes
Looks good, but please add a test case.

Do we need to handle network paths in other places?
Resolving?
Schema Validation for absolute paths?

btw. you can tests this with these kind of network paths: `\\?\C:\path\to\file`

2021-09-15 13:43 UTC, vankop commented
Thanks for your contribution. I am closing PR because it is too stale..

2021-09-15 13:43 UTC, closed without merging

2021-09-15 13:48 UTC, alexander-akait commented
@vankop I think we should open an issue for supporting `\\` windows UNC paths (https://docs.microsoft.com/ru-ru/dotnet/standard/io/file-path-formats#unc-paths), not high priority,