Fix #12255: compileBooleanMatcher fails when prefix and suffix overlap
webpack/webpack pull request #12256
Opened 2020-12-22 11:36 UTC by izaera

See #12225 for more info.

2020-12-22 12:39 UTC, izaera commented
Note: though it says it's pending, I have already signed the CLA.

2020-12-22 12:42 UTC, alexander-akait commented
Just bug on bot side, don't worry

2020-12-22 13:24 UTC, sokra requested changes

2020-12-22 13:24 UTC, sokra commented on lib/util/compileBooleanMatcher.js
> +			itemsArr.map(item => item.substring(prefix.length))
```suggestion
			itemsArr.map(item => item.slice(prefix.length))
```

2020-12-22 13:24 UTC, sokra approved these changes

2020-12-23 20:08 UTC, merged

2020-12-23 20:08 UTC, sokra commented
Thanks

2020-12-28 08:59 UTC, izaera commented
@sokra :+1: