Fix runtime type error in WatchIgnorePlugin
webpack/webpack pull request #12384
Opened 2021-01-10 22:09 UTC by Dico200

I started using WatchIgnorePlugin and it generates a runtime error like
```
TypeError: watcher.getContextInfoEntries is not a function
    at Object.getContextTimeInfoEntries
    at Watching.invalidate
```

**What kind of change does this PR introduce?**
This PR changes a callsite to use the correct function name

**Did you add tests for your changes?**
This is a blatant type error in master, as demonstrated by these searches: https://github.com/webpack/webpack/search?q=getContextTimeEntries
https://github.com/webpack/webpack/search?q=getContextTimeInfoEntries
Adding a test for this is pointless.

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
There is nothing to add to the documentation

2021-01-11 11:38 UTC, alexander-akait commented
Can you accept CLA?

2021-01-11 18:23 UTC, Dico200 commented
> Can you accept CLA?

I had done so yesterday. I checked today and it appears to have remembered that I did accept the CLA.

2021-01-11 20:48 UTC, sokra requested changes
You can "test" that, by adding type annotations to the constructor of this class. There is an `WatchFileSystem` interface somewhere around.

2021-01-11 21:16 UTC, sokra approved these changes

2021-01-12 01:10 UTC, snitin315 approved these changes

2021-01-12 07:12 UTC, merged

2021-01-12 07:12 UTC, sokra commented
Thanks