feat: add node: prefixed modules
webpack/webpack pull request #12693
Opened 2021-02-16 04:46 UTC by dnalborczyk

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2021-02-16 10:15 UTC, alexander-akait commented
Can you add small test?

2021-02-16 13:29 UTC, sokra requested changes

2021-02-16 13:29 UTC, sokra commented on lib/node/NodeTargetPlugin.js
> +builtins.push(...builtins.map(builtin => `node:${builtin}`));
```suggestion
	"zlib",
	/^node:/
];
```

2021-02-16 13:29 UTC, sokra commented
make to sure to also add a test case for that.

2021-02-18 14:55 UTC, sokra commented
hmm, seems like `node:` only works in `import` and not in `require`, but we always generate `require` calls for the node.js externals. We need to revisit that when ESM support allows module externals.

2021-03-11 20:11 UTC, dnalborczyk commented
> hmm, seems like `node:` only works in `import` and not in `require`, but we always generate `require` calls for the node.js externals. We need to revisit that when ESM support allows module externals.

@sokra

that's what I tried to explain here: https://github.com/webpack/webpack/pull/12181#issuecomment-745305067

this will be supported soon in node.js for commonjs modules as well (mentioned on top): https://github.com/nodejs/node/pull/37246

I thought **esm** support is currently being added to webpack? https://github.com/webpack/webpack/releases/tag/v5.22.0

2021-03-12 12:16 UTC, alexander-akait commented
@dnalborczyk I think we need wait when it was merged and we can merge it too

2021-03-26 00:21 UTC, dnalborczyk commented
> @dnalborczyk I think we need wait when it was merged and we can merge it too

@alexander-akait it's merged now. it seems it's being shipped in node v16.x and possibly backported later on.

2021-03-26 06:49 UTC, sokra commented
Ok node merged `node:` support for require, so this PR is fine now. A test case is still missing for that.

2021-05-06 09:21 UTC, karlhorky commented
This will close #13290 when merged

2021-05-19 19:24 UTC, alexander-akait commented
@dnalborczyk friendly ping

2021-05-30 09:18 UTC, karlhorky commented
So this feature is about to get more usage: the `node:` scheme / prefix / protocol was backported to Node.js 14.13.1 / 12.20.0 🎉

https://nodejs.org/api/esm.html -> link "node: Imports" (links with anchors don't scroll properly right now)

<img width="549" alt="Screen Shot 2021-05-30 at 11 04 39" src="https://user-images.githubusercontent.com/1935696/120098640-6104d200-c137-11eb-934d-3174e9e2afcc.png">

2021-05-30 09:27 UTC, karlhorky commented
An alternative to the approaches in #13311 and #12693 would be to use [`is-core-module`](https://github.com/inspect-js/is-core-module) (which was split from [`resolve`](https://github.com/browserify/resolve) in [browserify/resolve@7c26483](https://github.com/browserify/resolve/commit/7c26483)), so that this list doesn't need to be maintained and tested by `webpack` itself.

2021-06-18 09:12 UTC, sokra approved these changes

2021-06-21 08:06 UTC, merged

2021-06-21 08:06 UTC, sokra commented
Thanks

2021-06-21 08:16 UTC, karlhorky commented
Thanks @sokra! Looking forward to using this! (also with our students in Next.js!)

Will this be in a new patch (`5.39.2`) or minor (`5.40.0`)?

2021-09-07 07:57 UTC, fregante commented
I'm still seeing this issue on webpack 5.52

```
ERROR in node:path
Module build failed: UnhandledSchemeError: Reading from "node:path" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

[log clipped]

webpack 5.52.0 compiled with 1 error in 34836 ms
```

2021-09-07 11:37 UTC, alexander-akait commented
@fregante please create steps to reproduce, if you use `target: 'web'` it is expected, no `node:path` in browser

2021-09-07 11:40 UTC, fregante commented
Gotcha, I am using a web target. Is there no solution to this in webpack currently? https://npms.io/search?q=node+scheme+webpack

2021-09-07 11:41 UTC, alexander-akait commented
You can use alias and use https://github.com/browserify/path-browserify

2021-09-07 11:42 UTC, alexander-akait commented
But maybe better to ask developer provide browser based version of library

2021-09-07 11:46 UTC, fregante commented
The developer does, but it uses [`exports.browser` in the package.json](https://github.com/sindresorhus/filenamify/blob/43f3f32743df4c9230749a29b00f700ef4e93878/package.json#L16), which doesn't seem to be picked up and I wasn't able to find any issues regarding exports map on this repo either.

I'm using an alias in webpack for this but it's not a tenable solution if more packages come along.

2021-09-07 11:47 UTC, fregante commented
> You can use alias and use [browserify/path-browserify](https://github.com/browserify/path-browserify)

That's already configured. Are you saying that it can be handled completely by adding a specific `node:path` alias?

2021-09-07 11:48 UTC, alexander-akait commented
> The developer does, but it uses exports.browser in the package.json, which doesn't seem to be picked up and I wasn't able to find any issues regarding exports map on this repo either.

It will be used if it is provided

2021-09-07 11:52 UTC, fregante commented
> > You can use alias and use [browserify/path-browserify](https://github.com/browserify/path-browserify)
> 
> That's already aliased to `path` via [Richienb/node-polyfill-webpack-plugin](https://github.com/Richienb/node-polyfill-webpack-plugin). Are you saying that it can be handled completely by adding a specific `node:path` alias?

Answering myself, it doesn't work, same problem as before:

```js
module.exports = {
  target: "web",
  resolve: {
    fallback: {
      fs: false,
      crypto: false,
      console: false,
      vm: false,
      path: false,
      "node:path": false,
    },
    alias: {
      'node:path': "path-browserify",
    },
  },
```

2021-09-07 12:00 UTC, alexander-akait commented
Give me time, I will investigate

2021-09-07 12:13 UTC, fregante commented
I don't understand why you closed the issue. That's not a duplicate. I gave a full report including a demo repository avoiding to clutter an unrelated PR and you just locked it 🤷‍♂️

2021-09-07 12:14 UTC, fregante commented
They're two separate issues:

- node:path, being discussed here
- exports.browser, for which I opened https://github.com/webpack/webpack/issues/14163

2021-09-07 12:15 UTC, alexander-akait commented
Because the problem in other place, what is the problem wait the answer?

2021-09-07 12:21 UTC, alexander-akait commented
Change your import on `import * as mod from "filenamify/browser";`

2021-09-07 12:22 UTC, alexander-akait commented
Here described https://nodejs.org/api/packages.html#packages_subpath_exports

2021-09-07 12:23 UTC, alexander-akait commented
And we cannot analyze it is subpath for browser or not, so you should explicitly use `filenamify/browser`

2021-09-07 12:27 UTC, alexander-akait commented
But here other problem `resolve.fallback.path`/`resolve.fallback['node:path']` is not respected

2021-09-07 12:54 UTC, alexander-akait commented
Issue for `resolve.fallback` and `resolve.alias` https://github.com/webpack/webpack/issues/14166

2021-09-21 10:23 UTC, fregante commented
https://github.com/webpack/webpack/issues/14163 is showing up in search results. 

Please unlock the issue and explain that "browser" in the export map is not expected to work like the ["browser" field](https://github.com/defunctzombie/package-browser-field-spec). The current locking reason makes no sense.

2021-09-21 10:26 UTC, alexander-akait commented
I don't know what we need explain here, Node.js docs describe how `exports` works

2021-09-21 10:30 UTC, fregante commented
I’m stumped by your reasoning here. Webpack users will bump into that exact issue and there’s no explanation on it. It just does not work. Please be kind and add an explanation there, it’s free.

2021-09-21 10:31 UTC, fregante commented
https://xkcd.com/979/

2021-09-21 10:36 UTC, alexander-akait commented
Where we should docs it?

2021-09-21 10:40 UTC, fregante commented
In the issue itself

2021-09-21 10:49 UTC, alexander-akait commented
Here answer https://github.com/webpack/webpack/pull/12693#issuecomment-914258583, `exports` is just subpath of URL, we can't understand that code for browser or for node or for other env

2021-09-21 10:51 UTC, fregante commented
I think you're completely missing the point.

1. This PR is unrelated
2. https://github.com/webpack/webpack/issues/14163 is the issue that's missing a solution, and is not linked to this one
3. I'm not the one needing a solution anymore

2021-09-21 11:05 UTC, alexander-akait commented
> exports.browser in package.json is not automatically picked up on web target #14163 is the issue that's missing a solution, and is not linked to this one

And should not do it - `./browser` is part of URL, if you need special target change it on `browser`, i.e.:
```
{
	"exports": {
		"browser": "./browser.js",
		"default": "./index.js"
	}
}
```

No `./`

2021-09-21 11:08 UTC, fregante commented
…

Can you just unlock that issue? There's nothing to discuss here.

2021-09-21 11:10 UTC, alexander-akait commented
No need discussion, what is the problem? I answered the same multiple times, `./browser` will not and should not work as you expected, logic described in Node.js docs