Fix module concatenation renaming bug
webpack/webpack pull request #12720
Opened 2021-02-19 11:32 UTC by PAkerstrand

## Background

When using destructuring assignment in a module, in combination with a default assignment, it can cause the property looked up in the generated code to be different than the one in the source code _(it uses `newName`)_ if there's a identifier collision.

```js
// index.js
import modA from "./module-a";
import modB from "./config";

const { testProp = "defaultValue" } = modB;

modA();
console.log(testProp);
```
```js
// module-a.js

// In the real code, `stats` is read from another Webpack build
// for the client bundle, generated by `@loadable/webpack-plugin`
const stats = { testProp: 'valueFromSomeFile' };

const { testProp } = stats;

export default function printModuleAProp() {
  console.log(testProp);
}
```
```js
// config.js
export default {
  testProp: "configuredValue",
};
```

Generated code:

```js

/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
var __webpack_exports__ = {};

;// CONCATENATED MODULE: ./src/module-a.js
// In the real code, `stats` is read from another Webpack build
// for the client bundle, generated by `@loadable/webpack-plugin`
const stats = { testProp: 'valueFromSomeFile' };

const { testProp } = stats;

function printModuleAProp() {
  console.log(testProp);
}

;// CONCATENATED MODULE: ./src/config.js
/* harmony default export */ const config = ({
	testProp: "configuredValue",
});

;// CONCATENATED MODULE: ./src/index.js

const { src_testProp = "defaultValue" } = config;

printModuleAProp();
console.log(src_testProp);

/******/ })()
;
```

## Analysis

If the code looks like in the following picture
![image](https://user-images.githubusercontent.com/463105/108497666-1956ea80-72ac-11eb-94b7-0dc2d0e33d9f.png)

we get a AST tree with paths that look like this:
![ConcatenatedModule_js_—_concatenate-bug](https://user-images.githubusercontent.com/463105/108497611-ff1d0c80-72ab-11eb-95ef-c555b128b101.png)

In this case, the `Property` we want to change is at index `1`, which the code handles just fine.

However, the bug appears when you've got code that looks like this:
![image](https://user-images.githubusercontent.com/463105/108497702-2b388d80-72ac-11eb-8076-6f895eadeecf.png)

In that case, you get an AST that looks like the following:
![ConcatenatedModule_js_—_concatenate-bug](https://user-images.githubusercontent.com/463105/108497851-5fac4980-72ac-11eb-86fa-68de1c57198a.png)

In this case, the code generator will take the second branch inside of `lib/optimize/ConcatenatedModule.js`, and change the name of the property without aliasing it, causing the semantics to change. The reason for that is that we have an `AssignmentPattern` at index `1`, while the `Property` we want to change is now at index `2`.

## The fix

This PR simply adds an additional check for this condition, and creates output like this instead:

```diff
- const { src_testProp = "defaultValue" } = config;
+ const { testProp: src_testProp = "defaultValue" } = config;
```

Closes #12712 

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

None, this is expected behaviour

2021-02-19 12:50 UTC, PAkerstrand commented
I'm not sure how to get this test to pass? 
![image](https://user-images.githubusercontent.com/463105/108506493-29c19200-72b9-11eb-8982-c2e6319c2c0d.png)

I've clicked the details, and signed the CLA. If/when I visit it now everything is "inactive" and immutable, saying that I've signed it already
![image](https://user-images.githubusercontent.com/463105/108506597-5a093080-72b9-11eb-87a5-1c9306fdda77.png)

2021-02-19 13:02 UTC, alexander-akait commented
Sometimes bot is freeze, close/open helps

2021-02-19 17:25 UTC, sokra requested changes

2021-02-19 17:25 UTC, sokra commented on lib/optimize/ConcatenatedModule.js
> +								) {
let's make it a bit shorter

``` js
if (path && path.length > 1) {
    const maybeProperty = path[1].type === "AssignmentPattern" ? path[2] : path[1];
    if (maybeProperty.type === "Property" && maybeProperty.shorthand) {
        source.insert(r[1], `: ${newName}`);
        continue;
    }
}
source.replace(r[0], r[1] - 1, newName);
```

2021-02-22 07:46 UTC, merged

2021-02-22 07:46 UTC, sokra commented
Thanks