fix types: accept a readonly array for configuration options
webpack/webpack pull request #12818
Opened 2021-03-05 16:34 UTC by pcorpet

The webpack main function can get multiple configuration as an array. However this array doesn't need to be mutable. This fix makes it accept readonly arrays.

**What kind of change does this PR introduce?**

bugfix for typescript types declaration

**Did you add tests for your changes?**

No: I couldn't find typing tests.

**Does this PR introduce a breaking change?**

No: all types that were accepted before are still accepted, it accepts new types.

**What needs to be documented once your changes are merged?**

Nothing, this is a fix.

2021-03-05 17:05 UTC, sokra commented
This is a generated file. Look into lib/webpack.js or lib/index.js and fix it in the jsdocs comments

2021-03-05 19:45 UTC, pcorpet commented
> This is a generated file. Look into lib/webpack.js or lib/index.js and fix it in the jsdocs comments

Thanks @sokra , I hadn't noticed.

I'm now stuck on https://github.com/microsoft/TypeScript/issues/42768

```js
			if (Array.isArray(options)) {
				/** @type {MultiCompiler} */
				compiler = createMultiCompiler(options, options);
				watch = options.some(options => options.watch);
				watchOptions = options.map(options => options.watchOptions || {});
			} else {
				/** @type {Compiler} */
				compiler = createCompiler(options);
				watch = options.watch;
				watchOptions = options.watchOptions || {};
			}
```

The isArray only guards propery against mutable arrays, not readonly arrays (see the bug in Typescript for deeper details).
Maybe we could cast the type of options in the else branch?

2021-03-18 16:07 UTC, pcorpet commented
Can someone help me with the failing test please?

2021-03-19 08:19 UTC, sokra requested changes

2021-03-19 08:19 UTC, sokra commented on lib/webpack.js
> +				const webpackOptions = /** @type {WebpackOptions} */ options;
```suggestion
				const webpackOptions = /** @type {WebpackOptions} */ (options);
```

2021-05-17 14:25 UTC, sokra approved these changes

2021-05-19 05:03 UTC, closed without merging