Add a test case for resolve.fallback
webpack/webpack pull request #12827
Opened 2021-03-06 22:54 UTC by dmattia

**What kind of change does this PR introduce?**

This is an additional test for showing the `resolve.fallback` functionality, ensuring that it does not override packages that do already exist.

**Did you add tests for your changes?**

my changes are just a test

**Does this PR introduce a breaking change?**

nah

**What needs to be documented once your changes are merged?**

nothing

2021-03-07 18:29 UTC, sokra requested changes
Please make sure to add the email of your commit (david@transcend.io) to your github account and sign our CLA.

2021-03-07 18:51 UTC, dmattia commented
@sokra Awesome, thank you. I have added that email and signed the CLA

2021-03-08 08:14 UTC, sokra approved these changes

2021-03-08 08:14 UTC, merged

2021-03-08 08:14 UTC, sokra commented
Thanks