fix: es5
webpack/webpack pull request #12887
Opened 2021-03-13 14:23 UTC by alexander-akait

**What kind of change does this PR introduce?**

bugfix, but we still have `async` here, but not related to this fix

**Did you add tests for your changes?**

hard to test, I think we can use `acorn` to check syntax (try to parse based on `es` target), if we will face with it again I will write couple tests

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

No

2021-03-13 15:38 UTC, sokra requested changes
Use the runtimeTemplate.basicFunction or runtimeTemplate.returningFunction helpers instead of selecting based on arrow function. That makes it more readable and less prone to errors in the duplicated code

2021-03-13 16:29 UTC, alexander-akait commented on lib/runtime/AsyncModuleRuntimeModule.js
> -							"var queue = [], result;",
`result` is not used anywhere, so I just remove it

2021-03-13 16:30 UTC, alexander-akait commented on lib/runtime/CreateFakeNamespaceObjectRuntimeModule.js
>  			]),
Found more cases, refactored

2021-03-13 16:37 UTC, alexander-akait commented
@sokra Done

2021-03-14 02:26 UTC, xinggangling commented
> **What kind of change does this PR introduce?**
> 
> bugfix, but we still have `async` here, but not related to this fix, fixes #12885
> 
> **Did you add tests for your changes?**
> 
> hard to test, I think we can use `acorn` to check syntax (try to parse based on `es` target), if we will face with it again I will write couple tests
> 
> **Does this PR introduce a breaking change?**
> 
> No
> 
> **What needs to be documented once your changes are merged?**
> 
> No

`async` is also a problem; 
The ultimate goal of this issue is to avoid Es5 + syntax in the code。
IOS 9 WebView does not support

2021-03-14 02:32 UTC, xinggangling commented
> **What kind of change does this PR introduce?**
> 
> bugfix, but we still have `async` here, but not related to this fix, fixes #12885
> 
> **Did you add tests for your changes?**
> 
> hard to test, I think we can use `acorn` to check syntax (try to parse based on `es` target), if we will face with it again I will write couple tests
> 
> **Does this PR introduce a breaking change?**
> 
> No
> 
> **What needs to be documented once your changes are merged?**
> 
> No

`async` is also a problem; 
The ultimate goal of this issue is to avoid Es5 + syntax in the code。
IOS 9 WebView does not support

2021-03-15 11:29 UTC, alexander-akait commented
@xinggangling It is impossible, sorry, and out of scope PR, we have other issue for this

2021-03-15 11:40 UTC, xinggangling commented
> @xinggangling It is impossible, sorry, and out of scope PR, we have other issue for this

topLevelAwait cause this problem,we had improved 
our code.😃

2021-03-15 11:44 UTC, alexander-akait commented
@sokra I accidentally rewrite your changes using `force`, sorry :disappointed:

2021-03-15 15:41 UTC, sokra approved these changes

2021-03-15 16:02 UTC, merged

2021-03-15 16:02 UTC, sokra commented
Thanks