respect entry-specific library.type when exposing system context
webpack/webpack pull request #13654
Opened 2021-06-28 16:50 UTC by cjpearson

**What kind of change does this PR introduce?**

Fixes #13637. The `__system_context__` injection was not working when using entries with different `library.type` values.

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

2021-06-29 08:02 UTC, sokra requested changes

2021-06-29 08:02 UTC, sokra commented on lib/RuntimePlugin.js
> +							: globalLibrary.type;
```suggestion
					const libraryType =
						entryOptions &&
						entryOptions.library !== undefined
							? entryOptions.library.type
							: globalLibrary.type;
```

When a `library` is specified for an entry it overrides the global one, and doesn't merge with it.

2021-06-29 08:02 UTC, sokra commented
Please make sure to sign the CLA: https://cla.js.foundation/webpack/webpack?pullRequest=13654

2021-06-29 08:27 UTC, cjpearson commented
Thanks @sokra. I applied your suggestion and rebased. The CLA should be signed as well.

2021-11-05 09:40 UTC, cjpearson commented
@alexander-akait Is it possible to re-run the CI? I don't think the failures were related to this change.

2021-11-05 14:10 UTC, alexander-akait commented
@cjpearson Please accept CLA

2021-11-05 14:45 UTC, sokra approved these changes

2021-11-05 14:46 UTC, sokra commented
PR looks good, can be merge once CLA is signed.

2021-11-05 17:48 UTC, cjpearson commented
Thanks! Just signed it.

2021-11-05 20:29 UTC, merged