add node-module option for node.__file/dirname
webpack/webpack pull request #14247
Opened 2021-09-14 13:51 UTC by vankop

**What kind of change does this PR introduce?**

feature

closes #14072 

**Did you add tests for your changes?**

not yet

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

new options node.__filename=node-module / node.__dirname=node-module

generate `__filename` and `__dirname` for common js modules when output.module to
`fileURLToPath(import.meta.url)` and `fileURLToPath(import.meta.url + "/..")` respectively

2021-09-20 15:55 UTC, sokra requested changes

2021-09-20 15:55 UTC, sokra commented on test/configCases/output-module/node-globals/index.js
> +	expect(dir.slice(dir.lastIndexOf("/", dir.length - 2))).toBe("/node-globals/");
```suggestion
	expect(dir.slice(dir.lastIndexOf("/", dir.length - 2))).toMatch(/[\\/]node-globals[\\/]/);
```

2021-11-26 11:16 UTC, sokra reviewed
Found these old review comments... not sure if they are still relevant

2021-11-30 13:37 UTC, vankop commented on lib/dependencies/NodeUrlDependency.js
> +			new InitFragment(
did not fix this yet

2022-04-05 10:41 UTC, vankop commented on lib/dependencies/NodeUrlDependency.js
> +			new InitFragment(
fixed

2022-04-05 10:41 UTC, vankop commented on test/configCases/output-module/node-globals/index.js
> +	const match = dir.match(/[\\/][^\\/]+[\\/]$/);
done

2023-12-25 18:35 UTC, alexander-akait approved these changes
@vankop can you rebase, I think we can merge it and I am fine with it, thank you

2024-01-09 01:15 UTC, iamyamakin commented
@sokra do you mind if i create PR with a merge commit? I see a few conflicts between this branch and main:

- lib/NodeStuffPlugin.js;
- lib/config/defaults.js;
- schemas/WebpackOptions.check.js.

2024-01-09 03:06 UTC, snitin315 commented
I'll rebase this PR, no worries.

2024-01-09 13:56 UTC, alexander-akait commented
Yeah, feel free to send again, I am fine with the such improve

2024-01-10 11:56 UTC, merged