improve runtime template
webpack/webpack pull request #14784
Opened 2021-11-21 17:53 UTC by vankop

**What kind of change does this PR introduce?**

refactoring, feature

- add optional chaining support check
- add template string support check
- use template string in asset generator

**Did you add tests for your changes?**

not yet

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

nothing

2021-11-21 18:32 UTC, vankop commented on lib/asset/AssetGenerator.js
> +						assetPath = runtimeTemplate.templateString(
2 other ideas:
```js
runtimeTemplate.templateString(`%s ${filename} %s`, a, b)
```
```js
runtimeTemplate.templateString`${runtimeTemplate.runtimeValue(a)} ${filename} ${runtimeTemplate.runtimeValue(b)}`
```

2021-11-22 14:02 UTC, sokra requested changes

2021-11-22 14:02 UTC, sokra commented on lib/asset/AssetGenerator.js
> +						assetPath = runtimeTemplate.templateString(
Maybe:

```
runtimeTemplate.concatenation({ expr: a }, filename, { expr: b })
```

2021-11-22 14:02 UTC, sokra commented on lib/asset/AssetGenerator.js
> +						`${RuntimeGlobals.module}.exports = ${assetPath};`
Maybe rename it to `runtimeTemplate.concatenation` and let the function decide which representation is more efficient.

2021-11-22 15:00 UTC, vankop commented on lib/asset/AssetGenerator.js
> +						`${RuntimeGlobals.module}.exports = ${assetPath};`
I have created `runtimeTemplate.concatenation`

2021-11-26 08:14 UTC, sokra approved these changes

2021-11-26 08:26 UTC, vankop commented on lib/RuntimeTemplate.js
> -		if (numberOfExpressions >= Math.round(len / 2))
did not get in which case this approach is wrong..

2021-11-26 08:27 UTC, vankop commented on lib/RuntimeTemplate.js
> +		// e. g. `x${a}x${b}x${c}x` (3*3 = 9) is shorter than "x"+a+"x"+b+"x"+c+"x" (4+4+4 = 12)
ah.. yes..

2021-11-26 08:42 UTC, merged

2021-11-26 08:42 UTC, sokra commented
Thanks

2022-01-04 19:11 UTC, anomiex commented
This PR determines optionalChaining and templateLiteral support from the target, and uses optionalChaining and templateLiteral support if the config explicitly sets `output.environment`, but seems to have overlooked making a change near https://github.com/webpack/webpack/blob/ccecc17c01af96edddb931a76e7a3b21ef2969d8/lib/config/defaults.js#L892-L906 to default `output.environment` properly from the target properties.