Add 'outputPath' configuration option for resource asset modules
webpack/webpack pull request #15015
Opened 2021-12-17 14:16 UTC by Knagis

This introduces `outputPath` configuration option for resource asset modules. This provides compatibility with file-loader option - making sure that existing users of file-loader can more easily switch to using asset modules. In general, this option seems to be very reasonable requirement, considering that without it, providing custom public path per asset module does not seem to be that useful.

In future the option might be expanded to allow a callback function, same as `filename` and `publicPath` but since that can be done in non-breaking manner, this PR only adds the simplest case with static string.

**What kind of change does this PR introduce?**

New configuration option

**Did you add tests for your changes?**

Not yet, first need preliminary review of the feature.

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

The new configuration option should be documented in asset module page.

2021-12-17 15:43 UTC, Knagis commented
The covered scenario is something like this - where the different public paths require files to be split but it can't be done because of paths otherwise matching.

```
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  module: {
    rules: [
     {
       test: /something..\.png/,
       type: 'asset/resource',
       generator: {
          // put emitted files under `cdn1/*.png`
          // but at runtime request from `https://cdn1/app/*.png`

          filename: '[hash][ext][query]',
          outputPath: 'cdn1',
          publicPath: 'https://cdn1/app/'
       }
     },
     {
       test: /something-else..\.png/,
       type: 'asset/resource',
       generator: {
          // put emitted files under `cdn2/*.png`
          // but at runtime request from `https://cdn2/app/*.png`

          filename: '[hash][ext][query]',
          outputPath: 'cdn2',
          publicPath: 'https://cdn2/app/'
       }
     },
    ]
  },
};
```

2021-12-22 08:13 UTC, Knagis commented
@sokra could you please take a look at this? Just so I know if I should work on completing the PR (tests etc.)

2021-12-22 11:14 UTC, alexander-akait commented
@Knagis Can you rebase?

2021-12-22 12:15 UTC, Knagis commented
rebased

2022-01-10 13:10 UTC, sokra commented
I don't see a need for that option, you can already specify the output path via the `filename` option:

```
    rules: [
     {
       test: /something..\.png/,
       type: 'asset/resource',
       generator: {
          // put emitted files under `cdn1/*.png`
          // but at runtime request from `https://cdn1/app/*.png`

          filename: 'cdn1/[hash][ext][query]',
          publicPath: 'https://cdn1/app/'
       }
     },
     {
       test: /something-else..\.png/,
       type: 'asset/resource',
       generator: {
          // put emitted files under `cdn2/*.png`
          // but at runtime request from `https://cdn2/app/*.png`

          filename: 'cdn2/[hash][ext][query]',
          publicPath: 'https://cdn2/app/'
       }
     },
    ]
```

or also globally:

```
output: {
  assetModuleFilename: "assets/[hash][ext][query]"
}
```

2022-01-10 15:35 UTC, Knagis commented
The difference is that in your example, the files will have to be uploaded as

* https://cdn1/app/cdn1/image.png
* https://cdn2/app/cdn2/image.png

without the `outputPath` property there isn't an option to get

* https://cdn1/app/image.png
* https://cdn2/app/image.png

while keeping the files in separate output folders locally so that each can be deployed to their own server afterwards.

2022-01-17 16:56 UTC, sokra requested changes

2022-01-17 16:56 UTC, sokra commented on lib/asset/AssetGenerator.js
> +					);
```suggestion
					let outputFilename = filename;
					if (this.outputPath) {
						const { path, info } =
							runtimeTemplate.compilation.getAssetPathWithInfo(
								this.outputPath,
								{
									module,
									runtime,
									filename: sourceFilename,
									chunkGraph,
									contentHash
								}
							);
						assetInfo = mergeAssetInfo(assetInfo, info);
						outputFilename = path.posix.join(
							path,
							filename
						);
					}
```

2022-01-18 09:28 UTC, Knagis commented
@webpack-bot just wait a minute, i am not done yet 😆

2022-01-18 10:51 UTC, alexander-akait commented
We need rebase :smile:

2022-01-18 13:07 UTC, Knagis commented
Rebased and added unit test as well.

2022-01-19 08:37 UTC, sokra approved these changes

2022-01-19 13:30 UTC, merged

2022-01-19 13:30 UTC, sokra commented
Thanks