fix: pass package type to loader runner
webpack/webpack pull request #15198
Opened 2022-01-18 13:43 UTC by stefanprobst

this is an attempt to fix #13233, based on [this comment](https://github.com/webpack/webpack/issues/13233#issuecomment-827459873).

**What kind of change does this PR introduce?**

feature

**Did you add tests for your changes?**

no

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

2022-01-19 08:08 UTC, sokra requested changes

2022-01-19 08:08 UTC, sokra commented on lib/NormalModuleFactory.js
> +							type: resolveRequest.descriptionFileData.type,
`descriptionFileData` might be unset/missing when no package.json is there

2022-01-20 08:03 UTC, sokra requested changes
Please add a test case.

You can put it into `test/cases/loaders`

2022-01-20 08:03 UTC, sokra commented on lib/NormalModuleFactory.js
> +							type:
I think you also want to pass `"module"` when `/\.mjs$/i.test(parsedResult.loader)`.

And when it ends with `.cjs` you don't want to pass `"module"` even if the `descriptionFileData` contains that type

2022-01-26 10:43 UTC, alexander-akait commented
Tests are failed

2022-01-26 11:01 UTC, stefanprobst commented
i think i need some handholding how to properly test this. do you have any hints? thanks

2022-01-26 11:02 UTC, alexander-akait commented
Wierd, no good message, let's rerun

2022-01-26 11:08 UTC, alexander-akait commented
Very strange...

2022-01-31 08:24 UTC, otakustay commented
Is there anything I can help to proceed this forward? I tried to run these tests on my local computer and no segment fault is reported under Node 17.4.0 but has another test failed:

```
  ● ConfigTestCases › asset-modules › http-url › http-url should compile

    More errors (10 instead of 6) while compiling than expected:

    The following errors are unexpected:
    moduleIdentifier = /Users/otakustay/Downloads/webpack/test/configCases/asset-modules/http-url/ind...; moduleName = ./index.js; loc = 10:0-106; message = Module not found: Error: connect ECONNREFUSED 0.0.0.0:443
    while fetching https://raw.gi...; moduleId = ./index.js; moduleTrace = []; details = undefined; stack = ModuleNotFoundError: Module not found: Error: connect ECONNREFUSED 0.0.0.0:443
    while fetching https://raw.githubusercontent.com//webpack//webpack//main/CODE_OF_CONDUCT.md
```

2022-02-01 12:18 UTC, vankop commented on test/cases/loaders/esm-loader-type/test.filter.js
> +	return false;
maybe we could filter this spawning another `jest` process and catching exit code.. but it seems overengineering to me..

2022-02-01 12:21 UTC, vankop commented
@stefanprobst Thanks for starting PR. I have separated test cases, there is bug in running `import()` in jest currently

2022-02-14 20:16 UTC, jablko commented
@vankop Why is this PR preferable to [this simpler one](https://github.com/webpack/webpack/pull/14077)?

2022-02-14 20:22 UTC, vankop commented
@jablko here we also respect cjs, mjs extensions and this PR already has test cases.

2022-02-14 21:38 UTC, jablko commented
> @jablko here we also respect cjs, mjs extensions

#14077 respects `.cjs` and `.mjs` extensions.

> and this PR already has test cases.

What about revising this PR with the #14077 implementation (thereby retaining this PR's tests)?

2023-03-15 20:32 UTC, alexander-akait commented
@stefanprobst sorry for delay, can you rebase?

2023-03-22 14:45 UTC, TheLarkInn commented
@stefanprobst we're looking at either next release for first Wednesday of April for this release at latest. I'll review after I cut release today.

2023-03-23 08:12 UTC, alexander-akait reviewed
Something wrond with jest again, we really need to figure out how to update it...

2023-03-29 05:15 UTC, vankop commented on test/cases/loaders/esm-loader-type/test.filter.js
> +	return false;
I think yes

2023-04-08 18:45 UTC, alexander-akait commented
@stefanprobst Can you comment ESM to pass tests and put `TODO` there, thank you

2023-04-19 01:42 UTC, TheLarkInn commented
Congrats @stefanprobst on your first webpack contribution. 🚀 🥇 Thank you!

2023-04-19 01:43 UTC, merged