disallow global renaming in NodeStuffPlugin
webpack/webpack pull request #15404
Opened 2022-02-16 08:16 UTC by vankop

**What kind of change does this PR introduce?**

fixes #15401 

**Did you add tests for your changes?**

yes

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**
nothing

2022-02-16 08:29 UTC, vankop commented on lib/NodeStuffPlugin.js
> +						parser.hooks.canRename.for("global").tap(
there is no need to prevent renaming for `__dirname`/`__filename` since they should be always strings

2022-02-22 09:45 UTC, sokra requested changes
I think disabling renaming would break a scenario like:

``` js
var shouldBeGlobal = global;
expect(shouldBeGlobal.test).toBe("test");
```

---

Instead of disabling renaming, it would be better to handle renaming.

You can do that with the `rename` hook. On renaming I would expect the right side to be replaced with `__webpack_require__.g`.

I think that should do it:

					parser.hooks.rename.for("global").tap("NodeStuffPlugin", expr => {
						const dep = new ConstDependency(
							RuntimeGlobals.global,
							expr.range,
							[RuntimeGlobals.global]
						);
						dep.loc = expr.loc;
						parser.state.module.addPresentationalDependency(dep);
						return false;
					});

2022-02-22 11:30 UTC, sokra approved these changes

2022-02-22 11:30 UTC, sokra commented
Thanks

2022-02-22 11:30 UTC, merged