import.meta.webpackContext
webpack/webpack pull request #15446
Opened 2022-02-26 20:18 UTC by vankop

**What kind of change does this PR introduce?**

feature 
closes #15372 

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
`import.meta.webpackContext("directory", { recursive: boolean, regExp: RegExp, mode })` returns same as `require.context` but only for `javascript/auto`, `javascript/esm`

2022-02-28 07:24 UTC, sokra requested changes
Best see lib/dependencies/ImportParserPlugin.js how all these options need to be handled.

2022-02-28 07:24 UTC, sokra commented on lib/dependencies/ImportMetaContextDependencyParserPlugin.js
> +			}
We should throw an error for any unsupported or invalid property.

2022-02-28 07:24 UTC, sokra commented on lib/dependencies/ImportMetaContextDependencyParserPlugin.js
> +			switch (prop.key.name) {
There are a bunch of other options we want to support here:

* `chunkName`
* `include`
* `exclude`
* `prefetch`
* `preload`
* `exports`

2022-02-28 07:24 UTC, sokra commented on lib/dependencies/ImportMetaContextDependencyParserPlugin.js
> +				}
`mode` need to be handled directly during parsing in that plugin. It can't be passed to the dependency.

2022-03-01 14:39 UTC, sokra requested changes

2022-03-01 14:39 UTC, sokra commented on lib/dependencies/RequireContextPlugin.js
> +					new ImportMetaContextDependencyParserPlugin().apply(parser);
We should also add a parser option to disable that behavior:

``` js
					if (
						parserOptions.importMetaContext !== undefined &&
						!parserOptions.importMetaContext
					)
						return;
```

2022-03-01 14:39 UTC, sokra commented on lib/dependencies/RequireContextPlugin.js
> +				);
`RequireContextPlugin.js` sounds a bit like the wrong plugin name.

Best split that into a separate `ImportMetaContextPlugin.js`

2022-03-01 14:39 UTC, sokra commented on test/cases/chunks/context-weak/index.js
>  it("should not bundle context requires with asyncMode === 'weak'", function() {
copy that test case to keep the old require.context test too.

2022-03-01 14:49 UTC, vankop commented on lib/dependencies/ImportMetaContextDependency.js
> +ImportMetaContextDependency.Template = ModuleDependencyTemplateAsRequireId;
also is this correct one?

2022-03-03 08:03 UTC, sokra commented on lib/dependencies/ImportMetaContextPlugin.js
> +						parserOptions.importMetaContext !== undefined &&
This option need to be added to the schema

2022-03-03 08:07 UTC, sokra approved these changes

2022-03-03 08:07 UTC, merged

2022-03-24 17:12 UTC, Tofandel commented
There seems to be a bug when using it with a package

````js
  const locales = import.meta.webpackContext('@/locales', {
    recursive: false,
    regExp: /(en|hu)\.json$/i,
  });
  const vuetify = import.meta.webpackContext('vuetify/lib/locale', {
    recursive: false,
    regExp: /(en|hu)\.js$/i,
  });
```

First one works perfect, second one throws warning during compilation
```
 WARNING  Compiled with 2 warnings                                                                                                                                                                                             6:09:41 PM

 warning  in ./node_modules/vuetify/lib/locale/ ./node_modules/vuetify/lib/locale/ sync nonrecursive (en%7Chu)\.js$/

Module not found: Error: Can't resolve './node_modules/vuetify/lib/locale/vuetify/lib/locale/en.js' in '***'

 warning  in ./node_modules/vuetify/lib/locale/ ./node_modules/vuetify/lib/locale/ sync nonrecursive (en%7Chu)\.js$/

Module not found: Error: Can't resolve './node_modules/vuetify/lib/locale/vuetify/lib/locale/hu.js' in '***'

```

It seems to be using the context twice

2022-03-24 17:15 UTC, alexander-akait commented
@Tofandel Looks like yes, please open an issue, thanks

2022-03-24 17:36 UTC, Tofandel commented
Managed to get a minimal repro (funny enough only seems to happen with vue-cli) so will open one

2022-03-24 18:11 UTC, Tofandel commented
Got it to reproduce without vue-cli

Just adding this in the webpack config
```
const path = require('path')
module.exports = {
  resolve: {
    modules: [
      'node_modules',
      path.resolve(__dirname, './node_modules'),
    ]
  },
}
```

2022-03-25 12:29 UTC, Tofandel commented
Also, not really a bug, but just exploring this without a doc

I found that the default mode is `sync` and so if using `chunkName` without a `mode` it will have no effect, maybe we can change the default to 'lazy-once' if a chunkName is given?

```
const vuetify = import.meta.webpackContext('vuetify/lib/locale', {
  recursive: false,
  chunkName: 'locales', // This does nothing until we add mode: 'lazy'
  regExp: /(en|hu)\.js$/i,
});
```

2022-03-25 12:42 UTC, vankop commented
> Also, not really a bug, but just exploring this without a doc
> 
> I found that the default mode is `sync` and so if using `chunkName` without a `mode` it will have no effect, maybe we can change the default to 'lazy-once' if a chunkName is given? Otherwise I'd add a compilation warning if chunkName is given with a mode that doesn't use the chunkName
> 
> ```
> const vuetify = import.meta.webpackContext('vuetify/lib/locale', {
>   recursive: false,
>   chunkName: 'locales', // This does nothing until we add mode: 'lazy' or mode: 'lazy-once'
>   regExp: /(en|hu)\.js$/i,
> });
> ```

yeah, need to add a warning if not `lazy*` mode