Module federation Throw Error worked with HMR When Compile A Async Chunk
webpack/webpack pull request #15542
Opened 2022-03-17 06:53 UTC by wangjinyang

**What kind of change does this PR introduce?**
fixes [#15534](https://github.com/webpack/webpack/issues/15534)

**Did you add tests for your changes?**
no

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
no

2022-04-01 12:55 UTC, sokra requested changes
That looks good. Only a nitpick is to get the name of the property from the constants.

2022-04-01 12:55 UTC, sokra commented on lib/container/RemoteRuntimeModule.js
> +							`__webpack_require__.m[id] = ${runtimeTemplate.basicFunction("", [
```suggestion
							`${RuntimeGlobals.moduleFactories}[id] = ${runtimeTemplate.basicFunction("", [
```

2022-04-01 12:55 UTC, sokra commented on lib/container/RemoteRuntimeModule.js
> +							`__webpack_require__.m[id] = ${runtimeTemplate.basicFunction(
```suggestion
							`${RuntimeGlobals.moduleFactories}[id] = ${runtimeTemplate.basicFunction(
```

2022-04-01 14:32 UTC, wangjinyang commented on lib/container/RemoteRuntimeModule.js
> +							`__webpack_require__.m[id] = ${runtimeTemplate.basicFunction(
many thanks for tips

2022-04-04 09:25 UTC, sokra approved these changes

2022-04-04 09:25 UTC, merged

2022-04-04 09:25 UTC, sokra commented
Thanks