catch error in runAsChild callback
webpack/webpack pull request #15578
Opened 2022-03-23 15:42 UTC by vankop

**What kind of change does this PR introduce?**
closes #13624 

**Did you add tests for your changes?**
no need

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

2022-03-23 15:46 UTC, alexander-akait reviewed
Looks good, but I am afraid it can be breaking change... but for me it is valid behavior

2022-03-28 07:31 UTC, sokra requested changes

2022-04-01 13:25 UTC, sokra approved these changes

2022-04-01 13:26 UTC, merged

2022-04-01 13:26 UTC, sokra commented
Thanks