fix: fix the check of this._redirect
webpack/webpack pull request #15647
Opened 2022-04-10 11:25 UTC by zh-lx

**What kind of change does this PR introduce?**
the left of `!this._redirectTo !== undefined` is if type `boolean`, but it is compared to `undefined`.

**Did you add tests for your changes?**
no

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
no

2022-04-14 06:56 UTC, sokra requested changes

2022-04-14 06:56 UTC, sokra commented on lib/ExportsInfo.js
> +		if (!(this._redirectTo !== undefined)) {
```suggestion
		if (this._redirectTo === undefined) {
```

2022-04-14 06:56 UTC, sokra commented on lib/ExportsInfo.js
> +		if (!(this._redirectTo !== undefined)) {
```suggestion
		if (this._redirectTo === undefined) {
```

2022-05-02 14:05 UTC, zh-lx reviewed
it looks good

2024-01-04 14:49 UTC, alexander-akait approved these changes

2024-11-06 12:44 UTC, alexander-akait reviewed
Can you add a test case?

2024-11-06 13:46 UTC, zh-lx commented
> Can you add a test case?

Done!

2024-11-06 13:51 UTC, alexander-akait commented on test/ExportsInfo.unittest.js
> +});
Can we make a test with real code?

2025-08-20 15:10 UTC, alexander-akait commented
Thank you for this PR, already refactored in the main, so close

2025-08-20 15:10 UTC, closed without merging