Don't warn for `import` of optional dependencies
webpack/webpack pull request #15688
Opened 2022-04-20 10:19 UTC by schickling

Based on @sokra's suggestion, this PR silences warnings like the below of `import` statements of optional dependencies.

![image](https://user-images.githubusercontent.com/1567498/164206753-d3b26383-9ad1-4ddd-bdd5-20b32e589557.png)

![image](https://user-images.githubusercontent.com/1567498/164206766-272cd669-d597-4cec-ac0a-e59373f314f5.png)

2022-04-20 10:38 UTC, sokra requested changes
We need a test case for that

2022-04-20 10:38 UTC, sokra commented on lib/FileSystemInfo.js
> +													expected: false,
Only set this to `false` for the `import()` case, which is the `if (imp.d > -1)` case a few lines above.

2023-01-19 09:42 UTC, inflation commented
It's really annoying to see these warnings.

2024-01-09 13:27 UTC, closed without merging

2024-10-05 09:55 UTC, hen-den commented
Would it be possible to resolve this warning? It's not critical, but it does clutter the build process with warning messages. 

**In my case I get the following warning:**

`<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/.../node_modules/velite/dist/velite-B_2ACfq8.js for build dependencies failed at 'import(configUrl.href)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.`