fix: relative path to single runtime chunk
webpack/webpack pull request #16153
Opened 2022-08-15 23:49 UTC by ScriptedAlchemy

**What kind of change does this PR introduce?**

bugfix: wrong relative path to webpack runtime in entry chunks

fixes: https://github.com/webpack/webpack/issues/16143

**Did you add tests for your changes?**

No

**Does this PR introduce a breaking change?**

No
**What needs to be documented once your changes are merged?**

nothing

2022-08-15 23:50 UTC, ScriptedAlchemy commented on lib/esm/ModuleChunkFormatPlugin.js
> +											? "../".repeat(baseOutputName.length - 1)
length needs to be offset since repeat(0) would still place one `../`, when using length you are always getting an extra `../`

2022-08-16 01:07 UTC, alexander-akait approved these changes

2022-08-16 02:56 UTC, rishabh3112 approved these changes

2022-08-16 02:58 UTC, snitin315 approved these changes

2022-09-12 02:43 UTC, ScriptedAlchemy commented
Can we get this merged?

2022-11-09 10:05 UTC, sokra requested changes
This is not correct in general. The problem only happens if the filename contains extra slashes that doesn't affect the path. e. g. a leading slash or a double slash. That need to be normalized.

We have a helper for computing the `../../` prefix: getUndoPath
This should probably be used here and the issue should be fixed inside of getUndoPath.

2023-01-14 02:11 UTC, ScriptedAlchemy commented
Okay will take a look

2023-03-08 14:42 UTC, alexander-akait commented
@ScriptedAlchemy sorry for bothering you, do you want to finish? we want to do release soon, thank you

2023-03-11 21:05 UTC, ScriptedAlchemy commented
I'll work on it!

2024-07-11 16:29 UTC, closed without merging