fix: Add proper callback handling to Compiler readRecords function
webpack/webpack pull request #16301
Opened 2022-09-27 18:15 UTC by zookatron

If you run a Webpack build with the [recordsPath](https://webpack.js.org/configuration/other-options/#recordspath) setting enabled and a readRecords hook set, Webpack will hang forever because the callback is not properly being passed to the `asyncLib.parallel` call in this code path in readRecords.

**What kind of change does this PR introduce?**

A very small bug fix.

**Did you add tests for your changes?**

No.

**Does this PR introduce a breaking change?**

No.

**What needs to be documented once your changes are merged?**

Nothing.

2022-09-27 18:30 UTC, alexander-akait commented
Please run prettier, thank you

2022-09-27 19:23 UTC, zookatron commented
> Please run prettier, thank you

Done, sorry about that

2022-09-27 20:16 UTC, alexander-akait commented
Looks like we need to fix types or rewrite the callback...

2022-09-27 23:33 UTC, zookatron commented
> Looks like we need to fix types or rewrite the callback...

I see, I wrapped the callback in a thunk to fix the issue with the type propagation

2022-11-09 12:16 UTC, sokra approved these changes

2022-11-09 12:16 UTC, sokra requested changes
This should probably pass errors along

2022-11-09 12:16 UTC, sokra commented on lib/Compiler.js
> +					() => callback()
```suggestion
					err => callback(err)
```

2022-11-09 21:36 UTC, zookatron commented
> This should probably pass errors along

You're right I missed that `asyncLib.parallel` passes errors this way, that was my bad, this has been fixed

2023-04-12 14:44 UTC, closed without merging

2023-04-12 15:39 UTC, TheLarkInn commented
@zookatron I wanted to provide credit for you on this PR's work, so look forward to seeing your name in the release notes! Thanks for all your hard work.