fix: Fixes #18519 - makes DefinePlugin quieter under default log level
webpack/webpack pull request #18520
Opened 2024-06-19 18:48 UTC by sushruth

Fixes #18519 

**What kind of change does this PR introduce?**

Technically a bugfix but more like removing an annoying log.

**Did you add tests for your changes?**

~~This does not change any functionality and there is no test to check for verbosity of logs.~~ I was wrong. I am fixing related tests right now.

**Does this PR introduce a breaking change?**

No.

**What needs to be documented once your changes are merged?**

Default logging behavior of DefinePlugin - but that is already not documented, so no new behavior from the perspective of documentation. It would definitely be nice to add that to the docs.

2024-06-20 10:29 UTC, alexander-akait requested changes
> logger.info(...): for important information messages. These messages are displayed by default. Only use this for messages that the user really needs to see

> logger.log(...): for unimportant information messages. These messages are displayed only when user had opted-in to see them

So it works as expected

2024-06-20 15:33 UTC, sushruth commented
@alexander-akait I would argue that this definition fits well.

> logger.debug(...): for debugging information. These messages are displayed only when user had opted-in to see debug logging for specific modules

Repeating that one line of log with no other information or context to go with it, is causing more noise than giving useful information. I think if that line of log said where the code was replaced while debugging DefinePlugin, that would at least amount to useful information. 

I would also argue that if we definitely need a log, webpack must display one unique log line item per replaced variable for `logger.log` level while `logger.debug` could be used to say which exact file and what line it happens at. That way debugging is easier and regular operation is not aggressively verbose.

What are your thoughts on this?

2024-06-20 15:58 UTC, alexander-akait commented
I am fine with `logger.debug`

2024-06-20 15:58 UTC, alexander-akait commented
And other improvements

2024-06-20 17:16 UTC, alexander-akait commented on lib/DefinePlugin.js
> +	logger.info(`Replaced "${key}" with "${strCode}"`);
Please use `debug`

2024-06-20 17:20 UTC, sushruth commented on lib/DefinePlugin.js
> +	logger.info(`Replaced "${key}" with "${strCode}"`);
Done.

2024-06-20 17:34 UTC, sushruth commented
> And other improvements

I will try to open a separate PR for it since it involves a bit more logic. Thanks, @alexander-akait !

2024-06-21 12:05 UTC, alexander-akait approved these changes

2024-06-21 12:44 UTC, merged