feat: css webpackIgnoreComment
webpack/webpack pull request #18609
Opened 2024-07-24 18:39 UTC by faga295

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2024-07-30 19:04 UTC, alexander-akait reviewed
Please add all tests from css-loader

2024-08-05 17:13 UTC, faga295 commented
Now image-set can't pass string type like `image-set("./img1x.png" 1x);`, so a test case in css-loader now can't pass

2024-09-20 10:06 UTC, alexander-akait commented on lib/css/walkCssTokens.js
> +) => {
I think this is not a correct implementation, our parser is written according to the specification and we should almost not touch it, except adding callbacks

2024-09-20 10:06 UTC, alexander-akait commented on lib/css/walkCssTokens.js
> +				input.charCodeAt(pos + direction) === CC_SOLIDUS
It should be not changed

2024-09-20 10:07 UTC, alexander-akait commented on lib/css/CssParser.js
> +						if (!currentDeclaration) processDeclaration(input, start, end);
Wrong

2024-09-20 10:08 UTC, alexander-akait commented on lib/css/CssParser.js
> +						if (!currentDeclaration) processDeclaration(input, start, end);
You don't need at all extra processing, just use binary search before creation deps

2024-09-20 10:10 UTC, alexander-akait requested changes
This code should be simplified, you don't need extra processing, just add a comment callback, collect all comments and use binary search before creation of deps

2024-09-20 11:42 UTC, faga295 commented on lib/css/CssParser.js
> +								break;
```
.class {
  color: red;
  /** webpackIgnore: true */
  background: /** webpackIgnore: false */ url("./url/img.png")
}
```
`lineNeedIgnore` indicates last line webpackIgnore, `functionNeedIngore` indicates webpackIgnore before url(), if we don't collect this, I think we can parseComments from the end position of last declaration to the start position of url function, but this parse range is a little large, maybe could cause some bugs.

2024-09-20 11:45 UTC, faga295 commented on lib/css/CssParser.js
> +								break;
We should record some key positions instead of use `eatWhitespaceAndComments`

2024-09-20 12:05 UTC, alexander-akait commented on lib/css/CssParser.js
> +		};
It should be in `Cssparser`

2024-09-20 12:06 UTC, alexander-akait commented on lib/css/CssParser.js
> +				commentCallbacks
Always pass `callbacks` everything

2024-09-20 12:07 UTC, alexander-akait commented on lib/css/CssParser.js
> +	}
It should cssparser.js

2024-09-20 12:07 UTC, alexander-akait commented on lib/css/CssParser.js
> +	}
It should cssparser.js

2024-09-20 12:08 UTC, alexander-akait commented on lib/css/CssParser.js
> +								break;
You have `locConverter` to calculate line before

2024-09-20 12:11 UTC, alexander-akait reviewed
I have said many times that `walkCssTokens.js` changes should be minimal or even be absent, it will always lead to problems, the current logic is written according to the specification, and should not change at all

2024-09-20 15:03 UTC, faga295 commented on lib/css/CssParser.js
> +		};
I beleive this is in cssParser.js

2024-09-23 08:15 UTC, faga295 commented
I still reserve mulitple ignores like `declarationIgnore`,`needIgnore` and `stringIgnore`, which I think are necessary to pass all the related test cases in css-loader.However, the wrong changes of `walkCssTokens` are removed, and I use another way to implement this

2024-11-06 12:47 UTC, alexander-akait commented
Fixed

2024-11-06 12:47 UTC, closed without merging