Do not polyfill node bindings by default
webpack/webpack pull request #8460
Opened 2018-12-05 13:56 UTC by ooflorent

**What kind of change does this PR introduce?**

refactoring

**Did you add tests for your changes?**

yes

**Does this PR introduce a breaking change?**

yes

**What needs to be documented once your changes are merged?**

1. `node` has fewer options:
    - `global`
    - `__filename`
    - `__dirname`

2. `Buffer`, `setImmediate`, `process` and `console` are no longer polyfilled
3. `global` is still supported but is disabled by default
4. `require("vm")` or other node builtin packages are no longer polyfilled.  
Use `resolve.alias` instead.

2018-12-05 13:59 UTC, sokra approved these changes

2018-12-05 19:28 UTC, sokra requested changes
For improved migration we need a note in the error messages when a node.js module fails resolving.

2018-12-06 11:39 UTC, sokra requested changes

2018-12-06 11:39 UTC, sokra commented on lib/dependencies/GlobalDependency.js
> +exports.createGlobalDependency = range => {
Inline this code and remove the file.

2018-12-06 11:39 UTC, sokra commented on test/StatsTestCases.test.js
> +					.replace(new RegExp(path.join(base, testName), "g"), "Xdir/" + testName)
This doesn't work for windows paths and paths containing chars that need to be excaped.

2018-12-06 19:58 UTC, ooflorent commented
Please squash-merge, the history is lame.

2018-12-07 08:00 UTC, ooflorent commented
History is now clean

2018-12-08 11:23 UTC, merged

2026-05-10 20:22 UTC, TheKidCoder commented
@claude review

2026-05-10 20:38 UTC, TheKidCoder commented
@claude review

2026-05-10 20:39 UTC, TheKidCoder commented
@claude review

2026-05-10 20:40 UTC, TheKidCoder commented
@claude review

2026-05-10 20:42 UTC, TheKidCoder commented
@claude review